version: '3.8'

services:
  hackerbaybackend:
    image: hackerbaybackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file: .env
    ports:
      - 3000:3000
